default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  username: moses
  password: root

development:
  <<: *default
  database: zenki_development
test:
  <<: *default
  database: zenki_test

production:
  <<: *default
  database: zenki_production
